name: Deploy

on:
  push:
    branches:
    - master

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AKIA4TV646PXIRXRNS64 }}
          aws-secret-access-key: ${{ secrets.VvRgOKN27xjAFKVZ1n6bfQV3PHSOIB6VvzxujOLM }}
          aws-region: ${{ secrets.eu-west-2 }}
      - name: npm install
        env:
          CI: true
        run: |
          npm ci
      - name: deploy
        run: |
         npx ncc build index.ts
         zip -j deploy.zip ./dist/*
         aws lambda update-function-code --function-name=github-trial-task --zip-file=fileb://deploy.zip